### ISSUE TITLE
更新失败

### ISSUE THREAD

**Issue by Newblety** [WhaleFell/SMSBoom#14]
Traceback (most recent call last):
  File "smsboom_pyinstall.py", line 175, in <module>
  File "click\core.py", line 1130, in __call__
  File "click\core.py", line 1055, in main
  File "click\core.py", line 1657, in invoke
  File "click\core.py", line 1404, in invoke
  File "click\core.py", line 760, in invoke
  File "smsboom_pyinstall.py", line 158, in update
PermissionError: [Errno 13] Permission denied: 'D:\\Program Files\\SMS\\GETAPI.json'
[21192] Failed to execute script 'smsboom_pyinstall' due to unhandled exception!

**Comment by TomShiDi** [comment]
用管理员权限执行命令行

**Comment by WhaleFell** [comment]
如报错显示：`Permission denied` 大意为权限不足导致，请放在一个普通权限的文件夹，或者用管理员权限运行 EXE，谢谢您的支持。🤏🤏🤏
